In [66]:
'''importing the numpy module and random module'''

import numpy as np
import random

In [67]:
'''np.zeros(size_of_array) initilaizes an array of size size_of_array with values of all elements of array=0
and np.ones(size_of_array) initializes an array of size size_of_array with values of all elements of array=1'''

x=np.zeros(6)
y=np.ones(6)
print("array x:",x)
print("array y:",y)

array x: [0. 0. 0. 0. 0. 0.]
array y: [1. 1. 1. 1. 1. 1.]


In [68]:
'''random.randint(start,stop) is a function which will return a random number between start and 
stop,including both. Here we are using the function to give values to the elements of an array x randomly.'''

for i in range(x.size):
    x[i]=random.randint(0,100)
print("array x:",x)

array x: [79. 35. 89. 72. 92.  4.]


In [69]:
'''random.rand(size_of_array) initializes an array of size size_of_array with elements of array equal to
uniformly distributed random numbers whose values lies between 0 and 1

random.randn gives normally distributed random numbers whose values
lie between -Infinity to Infinity having 0 mean and 1 variance.'''

x=np.random.rand(6)
print("array x: \n",x,"\n")
y=np.random.randn(6)
print("array y: \n",y)

array x: 
 [0.7141191  0.26570303 0.13355497 0.41168068 0.05936861 0.45872339] 

array y: 
 [2.02860824 0.75115576 0.35436286 2.14052033 0.11026289 0.45215354]


In [70]:
'''np.mean(arr) returns the mean of all the elements of the array arr
   np.sum(arr) returns the sum of all the elements of the array arr
   np.min(arr) returns the minimum value from all elements in arr
   np.max(arr) returns the maximum value from all elements in arr'''

avg=np.mean(y)
sum_of_array=np.sum(y)
min_value=np.min(y)
max_value=np.max(y)
print("mean of array y is: ",avg)
print("sum of array y is: ",sum_of_array)
print("minimum value from array y is: ",min_value)
print("maximum value from array y is: ",max_value)

mean of array y is:  0.9728439379274777
sum of array y is:  5.837063627564866
minimum value from array y is:  0.11026288801279878
maximum value from array y is:  2.14052033224548


In [71]:
'''np.reshape() gives new shape to an array without changing its data'''

x1=x.reshape((3, 2))
y1=y.reshape((2, 3))
print("array x1: \n",x1,"\n")
print("array y1: \n",y1,"\n")

array x1: 
 [[0.7141191  0.26570303]
 [0.13355497 0.41168068]
 [0.05936861 0.45872339]] 

array y1: 
 [[2.02860824 0.75115576 0.35436286]
 [2.14052033 0.11026289 0.45215354]] 



In [72]:
'''As we can see, shape of x changed from (6,) to (3,2)'''

print("shape before reshaping: ",x.shape)
print("shape after reshaping: ",x1.shape)

shape before reshaping:  (6,)
shape after reshaping:  (3, 2)


In [73]:
'''np.concatenate() joins a sequence of arrays'''

z=np.concatenate((x,y))
print("array z: \n",z)

array z: 
 [0.7141191  0.26570303 0.13355497 0.41168068 0.05936861 0.45872339
 2.02860824 0.75115576 0.35436286 2.14052033 0.11026289 0.45215354]


In [74]:
'''np.argmax(arr,axis=n) Returns the indice of the maximum value in arr
   if axis is not specified, index is into the flattened array
   if axis=0, it searches along rows for max element
   if axis=0, it searches along columns for max element'''

arg1=np.argmax(x1)
arg2=np.argmax(x1,axis=0)
arg3=np.argmax(x1,axis=1)
print("index of max element when array is flattened:",arg1)
print("index of max element per column: ",arg2)
print("index of max element per row: ",arg3)

index of max element when array is flattened: 0
index of max element per column:  [0 2]
index of max element per row:  [0 1 1]


In [75]:
'''np.dot() function returns the dot product of 2 arrays.
In this case when both x and y are 1d Arrays, it returns the inner product of the the arrays'''

print("dot product of x and y:",np.dot(x,y))

dot product of x and y: 2.7907495960959174


In [76]:
'''In the below case when x1 is a 3*2 array and y1 is a 2*3 array, np.dot will return the result
which we get on matrix multiplication of x1 and y1,which is a 3*3 array'''

print("matrix multiplication of x1 and y1:\n",np.dot(x1,y1))

matrix multiplication of x1 and y1:
 [[2.01741063 0.56571186 0.37319585]
 [1.15214158 0.14571369 0.2334698 ]
 [1.10234241 0.09517524 0.22845144]]
